# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build IPA"
  lane :build_ipa do
    sh("flutter build ipa --release --no-codesign")
  end

  desc "Build IOS"
  lane :build_ios do
    sh("flutter build ios --release --no-codesign")
  end
end
