# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build APK"
  lane :build_apk do
    sh("flutter build apk --release --no-tree-shake-icons")
  end

  desc "Build AAB"
  lane :build_aab do
    sh("flutter build appbundle --release")
  end
end
